export const ROLES = {
  COMPLIANCE: "ROLE_COMPLIANCE",
  MODERATOR: "ROLE_MODERATOR",
  CUSTOMER_CARE: "ROLE_CUSTOMER_CARE",
  ADMIN: "ROLE_ADMIN",
  SALES: "ROLE_SALES",
  UNDER_WRITER: "ROLE_CREDIT",
};
